# Generated by Django 4.1.7 on 2023-03-06 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DB_Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('pin_code', models.BigIntegerField()),
                ('mobile', models.BigIntegerField()),
                ('income', models.TextField()),
                ('emp_type', models.CharField(max_length=200)),
                ('loan_amount', models.BigIntegerField()),
                ('salary_received', models.BigIntegerField()),
                ('date_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
