# Generated by Django 4.1.7 on 2023-03-06 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0005_alter_db_loan_first_name_alter_db_loan_income_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='db_loan',
            name='emp_type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='db_loan',
            name='salary_received',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
