# Generated by Django 4.1.7 on 2023-03-06 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0006_alter_db_loan_emp_type_alter_db_loan_salary_received'),
    ]

    operations = [
        migrations.AlterField(
            model_name='db_loan',
            name='emp_type',
            field=models.CharField(choices=[('Salaried', 'Salaried'), ('Self-employed', 'Self-employed'), ('Business Owner', 'Business Owner'), ('Other', 'Other')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='db_loan',
            name='mobile',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='db_loan',
            name='salary_received',
            field=models.CharField(choices=[('Bank Transfer', 'Bank Transfer'), ('Cash', 'Cash'), ('Chaque', 'Chaque')], max_length=50, null=True),
        ),
    ]
