# Generated by Django 4.1.7 on 2023-03-08 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0007_alter_db_loan_emp_type_alter_db_loan_mobile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DB_Become_Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200, null=True)),
                ('last_name', models.CharField(max_length=200, null=True)),
                ('mobile', models.CharField(max_length=200, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('city', models.CharField(max_length=200)),
                ('profession', models.CharField(max_length=200)),
                ('pan', models.CharField(max_length=50)),
            ],
        ),
    ]
