# Generated by Django 4.1.7 on 2023-03-08 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0008_db_become_partner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='db_become_partner',
            name='city',
            field=models.CharField(choices=[('Chh.Sambhajinagar', 'Chh.Sambhajinagar'), ('Pune', 'Pune'), ('Nashik', 'Nashik'), ('Mumbai', 'Mumbai'), ('Nagpur', 'Nagpur'), ('Latur', 'Latur')], max_length=200),
        ),
        migrations.AlterField(
            model_name='db_become_partner',
            name='profession',
            field=models.CharField(choices=[('Ex.Banker', 'Ex.Banker'), ('Chartered Accountant', 'Chartered Accountant'), ('Freelancer', 'Freelancer'), ('Finincial Analyst', 'Finincial Analyst'), ('Builder', 'Builder')], max_length=200),
        ),
    ]
