# Generated by Django 4.1.7 on 2023-03-08 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0010_db_become_partner_date_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DB_Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200, null=True)),
                ('last_name', models.CharField(max_length=200, null=True)),
                ('mobile', models.CharField(max_length=200, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('city', models.CharField(choices=[('Chh.Sambhajinagar', 'Chh.Sambhajinagar'), ('Pune', 'Pune'), ('Nashik', 'Nashik'), ('Mumbai', 'Mumbai'), ('Nagpur', 'Nagpur'), ('Latur', 'Latur')], max_length=200)),
                ('reason', models.CharField(choices=[('Complaints Related', 'Complaints Related'), ('Other', 'Other'), ('Document Issue', 'Document Issue'), ('Communication Address', 'Communication Address')], max_length=200)),
                ('subject', models.CharField(max_length=400)),
                ('message', models.TextField(max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='db_become_partner',
            name='profession',
            field=models.CharField(choices=[('Builder', 'Builder'), ('Finincial Analyst', 'Finincial Analyst'), ('Chartered Accountant', 'Chartered Accountant'), ('Ex.Banker', 'Ex.Banker'), ('Freelancer', 'Freelancer')], max_length=200),
        ),
    ]
